### ISSUE TITLE
junos.op.BGP missing

### ISSUE THREAD

**Issue by mmihir82** [ksator/python-training-for-network-engineers#1]
Hello Khelil,
I’m getting error when I import "from jnpr.junos.op.bgp import *”. I check the python module library (ls -al /usr/lib/python2.7/site-packages/jnpr/junos/op/) I couldn’t find it. Is there particular version that you are using so that I can download it.
Thanks for your help
Mihir M

**Comment by ksator** [comment]
@mmihir82 Hello,
tables and views (jnpr/junos/op subpackages) is available for many topics (vlan information, lldp neighbors information, isis adjacencies, route table, arp table, …) but not for everything. The package jnpr.junos.op doesn’t provide table and view for bgp). But you can easily add it.  
I updated the slides https://github.com/ksator/python-for-network-engineers/blob/master/Python-training.pdf.  
To add bgp to tables and views, just refer to the slide 200 and 201 from https://github.com/ksator/python-for-network-engineers/blob/master/Python-training.pdf.  
you need to build the bgp.yml file (slide 200) and you need to add the bgp.py as well (slide 201) to pythonify your yaml.
let me know if this issue can be closed  
Regards
Khelil

**Comment by mmihir82** [comment]
Thanks Khelil
